### PR TITLE
hal: ra: Initial support PWM

### PR DESCRIPTION
**Pull request by duynguyenxa**
Adding GPT library support for PWM driver for RA8

### CODE REVIEW

**Comment by ydamigos** [comment]
@thaoluonguw Could you please check it? I can't add you as a reviewer.

**Comment by thaoluonguw** [comment]
@duynguyenxa : Lack of compare match feature. Please re-check and update with source code of FSPv5.3.0

**Comment by duynguyenxa** [comment]
> @duynguyenxa : Lack of compare match feature. Please re-check and update with source code of FSPv5.3.0

@thaoluonguw , It's fixed

**Review by soburi — APPROVED** [review]

**Comment by thaoluonguw** [comment]
@duynguyenxa , @quytranpzz : Please fix conflict, I have no other comment. It looks good to me. Thank you.

**Comment by duynguyenxa** [comment]
@thaoluonguw @KhiemNguyenT , I've rebased the branch

**Review by KhiemNguyenT — APPROVED** [review]

**Pull request merged**
