### PR TITLE
hal: ra: Initial support for canfd

### PR DESCRIPTION
**Pull request by duynguyenxa**
Add fsp hal layer support for canfd module

### CODE REVIEW

**Comment by ydamigos** [comment]
@thaoluonguw Could you please check it? I can't add you as a reviewer.

**Comment by soburi** [comment]
> diff -r -u drivers/ra/fsp/src/r_canfd/r_canfd.c /home/crs/fsp/ra/fsp/src/r_canfd/r_canfd.c
> --- drivers/ra/fsp/src/r_canfd/r_canfd.c        2024-08-03 10:40:54.533527875 +0900
> +++ /home/crs/fsp/ra/fsp/src/r_canfd/r_canfd.c  2024-08-03 10:42:06.818070475 +0900
> @@ -280,10 +280,6 @@
>          /* Configure rule count for both channels */
>  #if BSP_FEATURE_CANFD_NUM_INSTANCES > 1
>          p_reg->CFDGAFLCFG0 = (CANFD_CFG_AFL_CH0_RULE_NUM << R_CANFD_CFDGAFLCFG0_RNC0_Pos);
> -        if (channel == 1)
> -        {
> -            p_reg->CFDGAFLCFG0 = (CANFD_CFG_AFL_CH1_RULE_NUM << R_CANFD_CFDGAFLCFG0_RNC0_Pos);
> -        }
>  #else
>          p_reg->CFDGAFLCFG0 = (CANFD_CFG_AFL_CH0_RULE_NUM << R_CANFD_CFDGAFLCFG0_RNC0_Pos) |
>                               CANFD_CFG_AFL_CH1_RULE_NUM;

Is it a Zephyr-specific change?
If so, please logging. 
https://github.com/zephyrproject-rtos/hal_renesas/pull/24#issuecomment-2265007009

**Review by soburi — APPROVED** [review]

**Comment by thenguyenyf** [comment]
Hi @soburi ,
For your comment in https://github.com/zephyrproject-rtos/hal_renesas/pull/28#issuecomment-2266322598, I have updated for it by a new commit. It's a bug fix for FSP v5.3.0 r_canfd. I also updated the patch note for it at here [drivers/ra/README](https://github.com/zephyrproject-rtos/hal_renesas/pull/28/files#diff-4d5b1892bc99be950f49b394ff8e2f66f3c25c40c3457bbc4fac70218c804fa8)

**Comment by thaoluonguw** [comment]
I am OK with these updates. Thank you.

**Review by KhiemNguyenT — APPROVED** [review]

**Pull request merged**
