### PR TITLE
hal: ra: Add RA8D1, RA8T1, SPI, Flash, ULPT, LPM, CGC, TRNG, I2C Hal layer support.

### PR DESCRIPTION
**Pull request by duynguyenxa**
- This PR update hal file to support BSP for RA8D1 and RA8T1 SOC series and module hal driver support for: SPI, Flash, ULPT, LPM, TRNG, I2C.

### CODE REVIEW

**Review by KhiemNguyenT — APPROVED** [review]
I reviewed it. Hope to receive more comments from others.

**Comment by ydamigos** [comment]
@soburi Could you please check the PR?

**Review by ydamigos — CHANGES_REQUESTED** [review]

**Comment by soburi** [comment]
It looks like there are diffs from fps v5.3.0.
If changes are needed, please make a commit with explaining the reason behind them. You will probably need to reapply them later when you bump the version up.

**Comment by ydamigos** [comment]
> It looks like there are diffs from fps v5.3.0. If changes are needed, please make a commit with explaining the reason behind them. You will probably need to reapply them later when you bump the version up.

@duynguyenxa Could you explain why there are diffs from FSP v5.3?

**Comment by duynguyenxa** [comment]
> > It looks like there are diffs from fps v5.3.0. If changes are needed, please make a commit with explaining the reason behind them. You will probably need to reapply them later when you bump the version up.
> 
> @duynguyenxa Could you explain why there are diffs from FSP v5.3?

@ydamigos , @soburi , cc: @thaoluonguw , Background is this development start before FSP v5.3.0 hasn't been released yet so the files previously are from FSP v5.2.0, when version up I miss the update for the SCE, now it's update to FSP v5.3.0, the only different now from v5.3.0 is the SCI_B_UART module which we have a minor change to DTC operation for it to work with Zephyr async API, we already separate the change for SCI_B_UART module in a different commit as @soburi  suggested.

**Comment by ydamigos** [comment]
> the only different now from v5.3.0 is the SCI_B_UART module which we have a minor change to DTC operation for it to work with Zephyr async API, we already separate the change for SCI_B_UART module in a different commit as @soburi suggested.

Should we log this change? ST does something similar. It keeps a README file with patch list.

**Review by ydamigos — APPROVED** [review]

**Comment by ydamigos** [comment]
@soburi Could you check again?

**Comment by soburi** [comment]
@ydamigos @duynguyenxa 

I confirmed it.

> Should we log this change? ST does something similar. It keeps a README file with a patch list.

@ydamigos 's suggestion makes sense.
It should be logged to README.
There are no other problems.

**Comment by duynguyenxa** [comment]
> @ydamigos @duynguyenxa
> 
> I confirmed it.
> 
> > Should we log this change? ST does something similar. It keeps a README file with a patch list.
> 
> @ydamigos 's suggestion makes sense. It should be logged to README. There are no other problems.

@ydamigos, @soburi , @KhiemNguyenT  , I added README file at 80a5a65189354c296c46c15e39f383443d55df39, please help to recheck

**Review by soburi — APPROVED** [review]

**Pull request merged**
